/**
 * API example
 * Sample API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface SampleDTO
 */
export interface SampleDTO {
    /**
     *
     * @type {number}
     * @memberof SampleDTO
     */
    id: number;
    /**
     *
     * @type {string}
     * @memberof SampleDTO
     */
    name: string;
}
/**
 * Check if a given object implements the SampleDTO interface.
 */
export declare function instanceOfSampleDTO(value: object): boolean;
export declare function SampleDTOFromJSON(json: any): SampleDTO;
export declare function SampleDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SampleDTO;
export declare function SampleDTOToJSON(value?: SampleDTO | null): any;
