/* tslint:disable */
/* eslint-disable */
/**
 * API example
 * Sample API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SampleDTO,
} from '../models';
import {
    SampleDTOFromJSON,
    SampleDTOToJSON,
} from '../models';

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     */
    async appControllerGetAllRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SampleDTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SampleDTOFromJSON));
    }

    /**
     */
    async appControllerGetAll(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SampleDTO>> {
        const response = await this.appControllerGetAllRaw(initOverrides);
        return await response.value();
    }

}
