/**
 * API example
 * Sample API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import type { SampleDTO } from '../models';
/**
 *
 */
export declare class DefaultApi extends runtime.BaseAPI {
    /**
     */
    appControllerGetAllRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SampleDTO>>>;
    /**
     */
    appControllerGetAll(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SampleDTO>>;
}
